apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: pokehub
spec:
  serviceName: "postgres-svc"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgres.database }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres.user }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pokehub-secrets
              key: postgres-password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata   # avoid permission issues
        resources:
          {{- toYaml .Values.postgres.resources | nindent 10 }}
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data

  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path    # k3s built-in provisioner
      resources:
        requests:
          storage: {{ .Values.postgres.storage }}