apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pokehub
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/afod3v/poke-hub
    targetRevision: main
    path: helm

  destination:
    server: https://kubernetes.default.svc
    namespace: pokehub

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true