api:
  image:
    repository: ghcr.io/afod3v/pokehub-api
    tag: "93d05a9d"
    pullPolicy: Always
  replicas: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  port: 3000
ui:
  image:
    repository: ghcr.io/afod3v/pokehub-ui
    tag: "93d05a9d"
    pullPolicy: Always
  replicas: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "250m"
  port: 4000
  origin: "https://poke-hub.eu"
postgres:
  image: postgres:16-alpine
  database: pokehub
  user: pokehub
  storage: 5Gi
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"
redis:
  image: redis:7-alpine
  storage: 1Gi
  resources:
    requests:
      memory: "32Mi"
      cpu: "50m"
    limits:
      memory: "64Mi"
      cpu: "100m"
ingress:
  enabled: true
  host: poke-hub.eu
  acmeEmail: roman@poke-hub.eu # used for Let's Encrypt cert expiry notifications
migrate:
  image:
    repository: ghcr.io/afod3v/pokehub-migrate
    tag: "93d05a9d"
    pullPolicy: Always
imagePullSecrets:
  - name: ghcr-secret
